apiVersion: v1
kind: Pod
metadata:
  name: video-demo-receiver
  labels:
    purpose: demonstrate_streaming
spec:
  containers:
  - name: receiver-demo-container
    image: paridhika/testimages:video-receiver2
    imagePullPolicy: Always
    ports:
        - name: video
          containerPort: 8001
          protocol: TCP
    