apiVersion: v1
kind: Pod
metadata:
  name: video-demo-receiver-raspbian
  labels:
    purpose: demonstrate_streaming
spec:
  containers:
  - name: receiver-demo-container-raspbian
    image: paridhika/testimages:video-receiver
    imagePullPolicy: Always
    command: ["node", "serverB.js"]
    args: ["localhost", "8001","8002"]
    ports:
    - name: video
      containerPort: 8002
      protocol: TCP
    