apiVersion: v1
kind: Pod
metadata:
  name: video-demo-receiver-raspbian
  labels:
    purpose: demonstrate_streaming
spec:
  containers:
  - name: receiver-demo-container-raspbian
    image: paridhika/testimages:video-receiver
    imagePullPolicy: Always
    command: ["node", "serverB.js"]
    args: ["192.168.64.3", "32049","8001"]
    ports:
    - name: video
      containerPort: 8001
      protocol: TCP
    