apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: streaming-deployment
spec:
  selector:
    matchLabels:
      app: video-demo
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: video-demo
    spec:
      containers:
      - name: sender-demo-containerA
        image: paridhika/testimages:video-sender-raspbian
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      - name: receiver-demo-containerB
        image: paridhika/testimages:video-receiver-raspbian
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
      - name: receiver-demo-containerC
        image: paridhika/testimages:video-receiver-raspbian
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
      - name: receiver-demo-containerD
        image: paridhika/testimages:video-receiver-raspbian
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
      - name: receiver-demo-containerE
        image: paridhika/testimages:video-receiver-raspbian
        imagePullPolicy: Always
        ports:
        - containerPort: 8004