apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sender-deployment
spec:
  selector:
    matchLabels:
      app: video-demo
  replicas: 1 
  template:
    metadata:
      labels:
        app: video-demo
    spec:
      containers:
      - name: sender-demo-container
        image: paridhika/testimages:video-sender-raspbian
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
    
      

