apiVersion: v1
kind: Pod
metadata:
  name: video-demo-sender-raspbian
  labels:
    purpose: demonstrate_streaming
spec:
  containers:
  - name: sender-demo-container-raspbian
    image: paridhika/testimages:video-sender
    imagePullPolicy: Always
    ports:
      - name: video
        containerPort: 3000
        protocol: TCP